name: oda_search_micro_journey
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  
  oda_fe_framework:
    git:
      url: https://github.com/corp-ais/next-oda-fe-framework
      ref: staging

  mya_ui_design:
    git:
      url: https://github.com/corp-ais/next-myais2-oda-myais-ui-design.git
      ref: staging

  oda_data_schema:
    git:
      url: https://github.com/corp-ais/next-myais2-oda-data-schema.git
      ref: feature/v245_enrich_next_core

  next_core:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging

  core_log:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_log

  core_language:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_language

  core_event:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_event

  core_network_websocket:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_network_websocket

  core_network_http:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_network_http

  core_interface:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_interface

  core_exception:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_exception

  core_data:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_data

  core_extension:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_extension

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  resumable_upload: ^0.0.2
  http: ^1.0.0
  web: ^0.5.1
  firebase_core: ^3.4.1

  oda_fe_framework:
    git:
      url: https://github.com/corp-ais/next-oda-fe-framework
      ref: staging

  mya_ui_design:
    git:
      url: https://github.com/corp-ais/next-myais2-oda-myais-ui-design.git
      ref: staging

  oda_data_schema:
    git:
      url: https://github.com/corp-ais/next-myais2-oda-data-schema.git
      ref: feature/v245_enrich_next_core

  next_core:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging

  core_log:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_log

  core_language:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_language

  core_event:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_event

  core_network_websocket:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_network_websocket

  core_network_http:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_network_http

  core_interface:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_interface

  core_exception:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_exception

  core_data:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l2_core_module/core_data

  core_extension:
    git:
      url: https://github.com/corp-ais/next-core.git
      ref: staging
      path: packages/l1_foundation/core_extension

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
